version: 2.1
orbs:
  node: circleci/node@5.2.0


jobs:
  checkoutEtTests:
    description: checkout et tests
    machine: true
    steps:
      - run: git clone https://github.com/tholach/LABO2_BACKEND.git
      - run: cd LABO2_BACKEND && npm install
      - run: cd LABO2_BACKEND && npm run test
  integrationFrontend:
    description: integration du frontend
    docker:
      - image: cimg/node:17.2.0
    steps:
      - run: git clone https://github.com/tholach/LABO2_FRONTEND.git
      - run: git clone https://github.com/tholach/LABO2_BACKEND.git
      - run: cd LABO2_FRONTEND && npm install
      - run: cd LABO2_FRONTEND && npm run build
      - run: mkdir -p LABO2_BACKEND/public
      - run: cp -rT LABO2_FRONTEND/build/ LABO2_BACKEND/public/
      - persist_to_workspace:
          root: .
          paths:
            - LABO2_BACKEND


  deploiement:
    description: deploiement
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run: ls -Rl



workflows:
  monWorkflow:
    jobs:
      - checkoutEtTests
      - integrationFrontend:
          requires:
            - checkoutEtTests
      - deploiement:
          requires: 
            - integrationFrontend